[package]
name = "lemon-rs"
version = "0.0.1"
authors = ["gwenn"]
description = "LALR(1) parser generator for Rust based on Lemon"
#documentation = "http://docs.rs/lemon-rs"
repository = "https://github.com/gwenn/lemon-rs"
readme = "README.md"
#categories = ["parser-implementations"]
keywords = ["sql", "parser", "sqlite"]
license = "Apache-2.0/MIT"
#build = "build.rs" # Lemon preprocessing

[features]
# FIXME: specific to one parser, not global
YYTRACKMAXSTACKDEPTH = []
YYNOERRORRECOVERY = []
YYSTACKDYNAMIC = []
NDEBUG = []

[dependencies]
# FIXME optional when NDEBUG
log = "0.4"
smallvec = "0.6"

#[build-dependencies]
#gcc = "0.3"
#lemon = "0.0.1"
